version: '3.8'

services:
  docker-demo-sqlserver:
    container_name: asset-management-sqlserver-container
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - asset-management-data:/var/opt/mssql     
  docker-demo-web-api:
    container_name: asset-management-container
    image: drfredchv/asset-management:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Server=asset-management-sqlserver-container;Database=AssetManagement_Rookies_B7_G3;User=${MSSQL_USER};Password=${MSSQL_SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
    ports:
      - "5000:8080"
    depends_on:
      docker-demo-sqlserver:
        condition: service_healthy
  docker-demo-frontend:
    container_name: asset-management-frontend-container
    image: drfredchv/asset-management-fe:latest
    environment:
      - VITE_API_URL=http://asset-management-container:5000  
    ports:
      - "80:80"  
    depends_on:
      docker-demo-web-api:
        condition: service_started
volumes:
  asset-management-data:
    driver: local
