name: Publish 

on: 
  workflow_dispatch:
  push:
    branches:
    - main 

env:
  AZURE_WEBAPP_NAME: dungdt-rookies-be
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true 

      - name: Restore
        run: dotnet restore "./AssetManagement.Api/AssetManagement.Api.csproj"

      - name: Build
        run: dotnet build "./AssetManagement.Api/AssetManagement.Api.csproj" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "./AssetManagement.Api/AssetManagement.Api.csproj" --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      
      - name: List published files
        run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"